# Generated by Django 5.2.7 on 2025-10-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='student_images')),
                ('embedding_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
